### ISSUE TITLE
TODO: UI for managing course state

### ISSUE THREAD

**Issue by moritz** [taustation-fan/university#13]
Now that state of University courses persists through reloads, it's probably easier to mark a course as in "done" or "in progress" state than to re-copy&paste the whole courses list.

So, ideally, we'd have a way to change a course's state, mostly for Not Done -> In Progress -> Done, but also the other way 'round in case somebody accidentally marks a course as Done.

**Comment by Perleone** [comment]
### Progress Report

In order to preserve course state in a sane fashion I had to refactor the whole parsing and storage mechanism, it went from raw text to JSON and Objects. With all that done and working the next step is to implement the actual state change.

**Comment by moritz** [comment]
Thanks @Perleone!

**Comment by Perleone** [comment]
I had to merge with giving my own branch priority over the newly introduced features to master. Which means there will **definitely** be some bugs and missing features. See also the commit message for d4a5a34.

**Comment by moritz** [comment]
Two things I've noticed so far:

* ~~Closing the course detail popup with the Escape key doesn't work anymore~~ (cannot reproduce this anymore)
* For the course that's "In Progress" from the `Enrolled in` copy&paste, the current course state and the button to modify it are out of sync. When it's in "In Progress", the state change button also says `Change to "In Progress"`, and when I press it a few times, the cycle is "In Progress", "Not Done", "Done"

**Comment by Perleone** [comment]
I cannot reproduce the problem with "In Progress", tried both Chromium and Firefox.
