### ISSUE TITLE
Wanted: Visualization of Dependencies

### ISSUE THREAD

**Issue by moritz** [taustation-fan/university#14]
It would be nice to have some kind of visualization of the dependency graph.

**Comment by duelafn** [comment]
I'm trying to commit a visualizaton script but get "Permission to taustation-fan/university.git denied to duelafn." The list of repositories (https://github.com/orgs/taustation-fan/teams/staff/repositories) shows university as only "Read" for me.

**Comment by moritz** [comment]
@duelafn fixed, thanks for the hint. You should now be able to push.
