### ISSUE TITLE
Todo: change the Done/Eligible columns to a Status Column

### ISSUE THREAD

**Issue by moritz** [taustation-fan/university#15]
Should the course that is running right now should show up as being eligible?

I'm of two minds, so please give me some input.

It seems, technically you are eligible for taking the course, otherwise you couldn't have started it. On the other hand, people use the eligibility filter for deciding what course to take next, and for that, it would make more sense to exclude it.

**Comment by duelafn** [comment]
As an alternat suggestion, I was thinking it might be better to reduce "Done" and "Eligible" to a single "Status" column which shows: ✔ for done, ✖ fo ineligible, ⏲ for the course in progress, and blank for eligible unfinished courses. Then, the in-progress course could be listed in both finished and unfinished listings (see a trial in the status-column branch).

**Comment by moritz** [comment]
I like the idea @duelafn

**Comment by moritz** [comment]
Thanks @duelafn, it's now deployed
