### ISSUE TITLE
Enforcer; class name misspelled

### ISSUE THREAD

**Issue by tmtowtdi** [taustation-fan/university#23]
I've taken the Enforcer, Short-barrel Master class on SoB but the table of untaken classes still lists it under "courses I have not done yet".  There's a spelling mismatch that I suspect is causing the problem; the class name is spelled

alpha.taustation.space -- Enforcer, Short-barrel Master
education.tauguide.de -- Enforcer, Short barrel rifle Master

**Comment by duelafn** [comment]
Renamed to match taustation.space. The change should make it to tauguide.de eventually.
